name: CashClash
version: '1.4'
main: me.psikuvit.cashClash.CashClashPlugin
api-version: '1.21'
description: A 4v4 PvP strategy minigame with economy mechanics
author: psikuvit
website: https://github.com/psikuvit/CashClash

commands:
  cashclash:
    description: Main Cash Clash command
    usage: /<command> [args]
    aliases: [cc]
    permission: cashclash.use
  party:
    description: Party management commands
    usage: /<command> <create|invite|accept|deny|leave|kick|transfer|disband|info|chat>
    aliases: [p]
    permission: cashclash.use

permissions:
  cashclash.use:
    description: Allows use of basic commands
    default: true
  cashclash.admin:
    description: Allows use of admin commands
    default: op
  cashclash.vip:
    description: VIP rank permissions
    default: false
  cashclash.mvp:
    description: MVP rank permissions
    default: false
  cashclash.clasher:
    description: Clasher rank permissions
    default: false
