package me.psikuvit.cashClash.config;

import me.psikuvit.cashClash.CashClashPlugin;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;

/**
 * Merges missing keys from the bundled (jar) resource files into the on-disk copies.
 * The bundled resource is the single source of truth for defaults, so any key added to a
 * resource file in a later plugin version is written to existing installs automatically,
 * instead of silently missing until the file is regenerated by hand.
 */
public final class ConfigMergeUtil {

    private ConfigMergeUtil() {
        throw new AssertionError("Utility class - do not instantiate.");
    }

    /**
     * Load a bundled resource as a YAML configuration. Returns null if the resource is missing.
     */
    public static FileConfiguration loadBundledResource(String resourcePath) {
        try (InputStream stream = CashClashPlugin.getInstance().getResource(resourcePath)) {
            if (stream == null) return null;
            return YamlConfiguration.loadConfiguration(new InputStreamReader(stream, StandardCharsets.UTF_8));
        } catch (Exception e) {
            CashClashPlugin.getInstance().getLogger().log(Level.WARNING,
                    "[CashClash] Failed to read bundled resource " + resourcePath, e);
            return null;
        }
    }

    /**
     * Copy every top-level key (and, recursively, nested sections) from {@code resource}
     * into {@code target} wherever the target doesn't already have it. Returns the dot-paths
     * of the keys that were added.
     */
    public static List<String> mergeAllMissing(FileConfiguration target, FileConfiguration resource) {
        List<String> added = new ArrayList<>();
        if (resource == null) return added;

        for (String key : resource.getKeys(false)) {
            Object value = resource.get(key);
            if (value instanceof ConfigurationSection section) {
                mergeSection(section, target, key, added);
            } else {
                mergeValue(target, key, value, added);
            }
        }
        return added;
    }

    private static void mergeSection(ConfigurationSection defaultsSection, FileConfiguration target, String path, List<String> added) {
        if (defaultsSection == null) return;

        for (String key : defaultsSection.getKeys(false)) {
            String fullPath = path + "." + key;
            Object value = defaultsSection.get(key);

            if (value instanceof ConfigurationSection) {
                mergeSection(defaultsSection.getConfigurationSection(key), target, fullPath, added);
            } else {
                mergeValue(target, fullPath, value, added);
            }
        }
    }

    private static void mergeValue(FileConfiguration target, String path, Object defaultValue, List<String> added) {
        if (!target.contains(path)) {
            target.set(path, defaultValue);
            added.add(path);
        } else if (defaultValue instanceof List && !((List<?>) defaultValue).isEmpty()
                && target.isList(path) && target.getList(path).isEmpty()) {
            // Refill a list that the admin left empty so the feature keeps working.
            target.set(path, defaultValue);
            added.add(path);
        }
    }
}
